name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  backend-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies 
        run: npm install  
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend 
    steps:
      - uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: npm install
      - run: npm run build
  deployment:
    needs: [backend-install, frontend-build]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && ! contains( join(github.event.commits.*.message), '#skip') }}    
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  notify_success:
    needs: [deployment]
    runs-on: ubuntu-latest
    steps:
      - name: notify success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Deployment success"
          content: ✅ *Deployment Successful!* 
          description: "[Link to commit](${{ github.event.head_commit.url }})"
          color: 0x008000
  tag_release:
    needs: [test_and_build, deployment]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && ! contains( join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          PRERELEASE: true
          DEFAULT_BUMP: patch
          DRY_RUN: true